const RECIPIENT_ADDRESS = "8veakRFJsUJ4dvVeKHSko37ATuVnYw7LrEjAA1iYkJ1F"
const MEMO_PROGRAM_ADDRESS = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
const TOKEN_MINT_ACCOUNT_ADDRESS = "7PAUfndKEDiMERakaVA3J7uEFNYRB8gTmqhCA79CkYyd"
const RECIPIENT_ASSOCIATED_TOKEN_ACCOUNT_ADDRESS = "Ap5amTR1D2VswUeG9rJHhHTUSBeC5C1GqTAhXAETUJY3"
const TOKEN_METADATA_PROGRAM_ID_ADDRESS = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

export {
    RECIPIENT_ADDRESS,
    MEMO_PROGRAM_ADDRESS,
    TOKEN_MINT_ACCOUNT_ADDRESS,
    RECIPIENT_ASSOCIATED_TOKEN_ACCOUNT_ADDRESS,
    TOKEN_METADATA_PROGRAM_ID_ADDRESS,
}
